openapi: 3.0.1
info:
  title: API para Carritos
  description: API para manejar carritos en la ecommerce
  version: 1.0.0
paths:
  /api/cartsDB/:
    get:
      summary: Obtiene todos los carritos
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Carritos obtenidos correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartArray'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

    post:
      summary: Crea un carrito
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        "200":
          description: Carrito creado correctamente en la base de datos
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/cartsDB/{cartId}/:
    get:
      summary: Obtiene un carrito específico
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: El ID del carrito
      responses:
        "200":
          description: Carrito obtenido correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/cartsDB/{cartId}/product/{pid}:
    post:
      summary: Agrega un producto al carrito
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: El ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto a agregar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: La cantidad del producto a agregar
              required:
                - quantity
      responses:
        "200":
          description: Carrito modificado correctamente en la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  cart:
                    $ref: '#/components/schemas/Cart'
        "400":
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Parámetros inválidos
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error interno del servidor

    put:
      summary: Modifica la cantidad de un producto en el carrito
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: El ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: La nueva cantidad del producto
              required:
                - quantity
      responses:
        "200":
          description: Cantidad del producto actualizada correctamente en el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: '#/components/schemas/Cart'
        "400":
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Se requiere una cantidad válida
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error al actualizar la cantidad del producto en el carrito

    delete:
      summary: Elimina un producto del carrito
      tags: 
        - Carritos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: El ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto a eliminar
      responses:
        "200":
          description: Producto eliminado correctamente del carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto eliminado del carrito correctamente
        "400":
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: ID del carrito o producto no válido
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error al eliminar el producto del carrito

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado de Mongo
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: '#/components/schemas/Product'
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
      example:
        _id: "60c72b2f9b1e8b3f8b2f8b3f"
        products: 
          - product: 
              _id: "60c72b2f9b1e8b3f8b2f8b3f"
              name: "Producto de ejemplo"
              category: "Categoría de ejemplo"
              availability: "Disponible"
              price: 100.0
            quantity: 5

    CartArray:
      type: array
      items:
        $ref: '#/components/schemas/Cart'